---
title: "Data Visualizations"
author: "Ramin"
date: "December 4, 2017"
output: pdf_document
---




```{r, echo=FALSE}
#creating geom gitter with col for gender and facet_grid for gender
install.packages("ggplot2")
library(ggplot2)
library(readxl)
joint_unemployment_total <- read_excel("~/Desktop/Autumn 2017/Statistics 321/unemployment rate/joint_unemployment_total.xlsx")
ggplot(joint_unemployment_total, aes(x = year, y = value, col = gender)) + 
  geom_jitter() + 
  facet_grid(. ~ gender) +
  labs(title = "Unemployment Rate in Iran by Gender", y = "Percentage", x = "Year") + geom_smooth(method = 'lm')

ggplot(joint_unemployment_total, aes(x = year, y = jitter(value), col = gender)) + 
  geom_point() +
  labs(title = "Unemployment Rate in Iran by Gender", y = "Percentage", x = "Year") + geom_smooth(method = 'lm') +
  scale_x_continuous(breaks = c(2000, 2002, 2004, 2006, 2008, 2010, 2012, 2014))

```


```{r, echo=FALSE}
# the fist appropriate plot for general audiance
ggplot(joint_unemployment_total, 
       aes(x = year,
           y = value,
           fill = gender)) +
  geom_bar(stat = "identity", 
           position = "dodge") +
  theme_get() +
  labs(title = "Unemployment Rate in Iran by Gender", y = "Percentage", x = "Year")  

```





```{r, echo=FALSE}

# the second appropriate plot for general audiance
ggplot(joint_unemployment_total, 
       aes(x = year, 
           y = value,
           color = gender)) +
  geom_line(size = 1.5) +
  labs(title = "Unemployment Rate in Iran by Gender", y = "Percentage", x = "Year") 
```



